# Generated by Django 5.0.6 on 2024-06-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="NoNickname", max_length=80)),
                ("task", models.CharField(default="NoTask", max_length=255)),
            ],
        ),
    ]
