# Generated by Django 5.0.6 on 2024-06-01 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0002_usertasks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTasks",
        ),
    ]
